name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main  # The current branch (hardcoded)
  schedule:
    - cron: '0 */6 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        run: |
          # Replace USERNAME with your GitHub username
          REPOS=(
            "https://purge.jsdelivr.net/gh/Yuzuk1Shimotsuki/live2d-widget@latest/autoload.js"
            "https://purge.jsdelivr.net/gh/Yuzuk1Shimotsuki/live2d-widget@latest/waifu-tips.js"
            "https://purge.jsdelivr.net/gh/Yuzuk1Shimotsuki/live2d-widget@latest/waifu.css"
            "https://purge.jsdelivr.net/gh/Yuzuk1Shimotsuki/live2d-widget@latest/live2d.min.js"
            "https://purge.jsdelivr.net/gh/Yuzuk1Shimotsuki/live2d-widget@latest/waifu-tips.json"
            "https://purge.jsdelivr.net/gh/Yuzuk1Shimotsuki/live2d-widget@latest/"
            "https://purge.jsdelivr.net/gh/Yuzuk1Shimotsuki/live2d_api-zh-TW@latest/"
          )
          
          failed=0
          for url in "${REPOS[@]}"; do
            echo "Purging cache for $url"
            response=$(curl -s "$url")
            if echo "$response" | grep -q '"success":false'; then
              echo "Error purging $url:"
              echo "$response"
              failed=1
            else
              echo "Successfully purged $url"
            fi
            sleep 1
          done
          
          if [ $failed -eq 1 ]; then
            exit 1
          fi
